/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 01-окт-2018 9:53:39 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 
 

/* Drop Tables */

DROP TABLE IF EXISTS city CASCADE
;

DROP TABLE IF EXISTS counter_data CASCADE
;

DROP TABLE IF EXISTS counters CASCADE
;

DROP TABLE IF EXISTS personal_account CASCADE
;

DROP TABLE IF EXISTS profile CASCADE
;

DROP TABLE IF EXISTS service CASCADE
;

DROP TABLE IF EXISTS service_provider CASCADE
;

DROP TABLE IF EXISTS tariff CASCADE
;

/* Create Tables */

CREATE TABLE city
(
	city_id bigserial NOT NULL,
	city_name varchar(255) NOT NULL,
	active boolean NOT NULL
)
;

CREATE TABLE counter_data
(
	counter_data_id bigserial NOT NULL,
	date date NOT NULL,
	counter_data real NOT NULL,
	counter_id bigint NULL
)
;

CREATE TABLE counters
(
	counter_id bigserial NOT NULL,
	counter_name varchar(50) NOT NULL,
	active boolean NOT NULL,
	unit_of varchar(10) NOT NULL,
	personal_account_id bigserial NOT NULL
)
;

CREATE TABLE personal_account
(
	personal_account_id bigserial NOT NULL,
	account_name varchar(50) NOT NULL,
	account_number varchar(255) NOT NULL,
	account_address varchar(255) NULL,
	active boolean NOT NULL,
	firstname varchar(50) NULL,
	lastname varchar(50) NULL,
	patronymic varchar(50) NULL,
	profile_id bigserial NOT NULL,
	registration_date date NOT NULL
)
;

CREATE TABLE profile
(
	profile_id bigserial NOT NULL,
	telephone varchar(11) NULL,
	email varchar(255) NOT NULL,
	password varchar(255) NOT NULL,
	active boolean NOT NULL,
	activation_code varchar(255) NULL,
	registration_date date NULL,
	username varchar(50) NOT NULL
)
;

CREATE TABLE service
(
	service_id bigint NOT NULL,
	service_name varchar(50) NULL,
	service_provider_id bigserial NOT NULL
)
;

CREATE TABLE service_provider
(
	service_provider_id bigserial NOT NULL,
	service_provider_name varchar(255) NOT NULL,
	service_provider_address varchar(255) NULL,
	description text NULL,
	active boolean NOT NULL,
	city_id bigserial NOT NULL
)
;

CREATE TABLE tariff
(
	tariff_id bigserial NOT NULL,
	tariff_name varchar(255) NOT NULL,
	tariff_sum real NOT NULL,
	tariff_date date NOT NULL,
	service_id bigint NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE city ADD CONSTRAINT PK_city_id
	PRIMARY KEY (city_id)
;

ALTER TABLE counters ADD CONSTRAINT PK_counter_id
	PRIMARY KEY (counter_id)
;

ALTER TABLE personal_account ADD CONSTRAINT PK_personal_account
	PRIMARY KEY (personal_account_id)
;

ALTER TABLE profile ADD CONSTRAINT PK_profile
	PRIMARY KEY (profile_id)
;

ALTER TABLE service ADD CONSTRAINT PK_service_id
	PRIMARY KEY (service_id)
;

ALTER TABLE service_provider ADD CONSTRAINT PK_service_provider_id
	PRIMARY KEY (service_provider_id)
;

ALTER TABLE tariff ADD CONSTRAINT PK_tariff_id
	PRIMARY KEY (tariff_id)
;

/* Create Foreign Key Constraints */

ALTER TABLE counters ADD CONSTRAINT FK_counters_personal_account
	FOREIGN KEY (personal_account_id) REFERENCES personal_account (personal_account_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE personal_account ADD CONSTRAINT FK_profile_id
	FOREIGN KEY (profile_id) REFERENCES profile (profile_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE service ADD CONSTRAINT FK_service_service_provider
	FOREIGN KEY (service_provider_id) REFERENCES service_provider (service_provider_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE service_provider ADD CONSTRAINT FK_service_provider_city
	FOREIGN KEY (city_id) REFERENCES city (city_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE tariff ADD CONSTRAINT FK_tariff_service
	FOREIGN KEY (service_id) REFERENCES service (service_id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

 

 

 

 

 

 

 

 

 

 

 
